### ISSUE TITLE
allow owner to append more options

### ISSUE THREAD

**Issue by ngzhian** [kiangkuang/WhoPick#1]
Original feature request is to allow participants to add options, but that may be very messy, so instead allow owners to update the poll with options.

**Comment by kiangkuang** [comment]
I'm thinking of an inline-keyboard to allow editing of the entire poll
```
admin > Share poll
      > Update results
      > Edit poll > Edit question
                  > Add option
                  > Remove option
      > Close poll
```

**Comment by kiangkuang** [comment]
Implemented
